from appwrite.client import Client
from appwrite.services.databases import Databases
import os
from dotenv import load_dotenv

load_dotenv()

#setting secret data here
SECURITY_KEY = os.getenv('SECURITY_KEY')
ALGORITHM = os.getenv('ALGORITHM')
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv('ACCESS_TOKEN_EXPIRE_MINUTES'))

#database connection keys
APPWRITE_ENDPOINT = 'https://cloud.appwrite.io/v1'
APPWRITE_PROJECT_ID = os.getenv('APPWRITE_PROJECT_ID')
APPWRITE_API_KEY = os.getenv('APPWRITE_API_KEY')
APPWRITE_DATABASE_ID = os.getenv('APPWRITE_DATABASE_ID')
APPWRITE_COLLECTION_ID = os.getenv('APPWRITE_COLLECTION_ID')
APPWRITE_EMPLOYEE_COLLECTION_ID = os.getenv('APPWRITE_EMPLOYEE_COLLECTION_ID')
APPWRITE_REQUEST_HEADER_COLLECTION_ID = os.getenv('APPWRITE_REQUEST_HEADER_COLLECTION_ID')
APPWRITE_REQUEST_DETAILS_COLLECTION_ID = os.getenv('APPWRITE_REQUEST_DETAILS_COLLECTION_ID')
APPWRITE_PRODUCT_COLLECTION_ID = os.getenv('APPWRITE_PRODUCT_COLLECTION_ID')
APPWRITE_CATEGORY_COLLECTION_ID = os.getenv('APPWRITE_CATEGORY_COLLECTION_ID')
APPWRITE_MEASURE_UNIT_COLLECTION_ID = os.getenv('APPWRITE_MEASURE_UNIT_COLLECTION_ID')
APPWRITE_AUDIT_TRAIL_COLLECTION_ID = os.getenv('APPWRITE_AUDIT_TRAIL_COLLECTION_ID')
APPWRITE_SUPPLIER_COLLECTION_ID = os.getenv('APPWRITE_SUPPLIER_COLLECTION_ID')
APPWRITE_USER_COLLECTION_ID = os.getenv('APPWRITE_USER_COLLECTION_ID')

client = Client()
client.set_endpoint(APPWRITE_ENDPOINT)
client.set_project(APPWRITE_PROJECT_ID)
client.set_key(APPWRITE_API_KEY)

database = Databases(client)